# Generated by Django 3.1.14 on 2022-05-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About_Me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='About_Me',
            new_name='about_me',
        ),
    ]
